# Generated by Django 5.0 on 2023-12-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_nextdoor_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preorder',
            name='packed',
            field=models.BooleanField(default=False),
        ),
    ]
