# Generated by Django 5.0 on 2024-01-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_nextdoor_api', '0005_remove_preorder_test_quantity_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder_test',
            name='item',
        ),
        migrations.AddField(
            model_name='preorder_test',
            name='item',
            field=models.ManyToManyField(through='market_nextdoor_api.Preorder_testItem', to='market_nextdoor_api.item'),
        ),
    ]
