# Generated by Django 5.0 on 2024-01-06 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_nextdoor_api', '0006_remove_preorder_test_item_preorder_test_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorder_test',
            old_name='item',
            new_name='items',
        ),
    ]
