# Generated by Django 5.0 on 2024-01-11 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_nextdoor_api', '0009_rename_preorder_testitem_preorder2item_preorder2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer2Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_nextdoor_api.customer2')),
            ],
        ),
        migrations.CreateModel(
            name='Market2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendors', models.ManyToManyField(through='market_nextdoor_api.Customer2Market', to='market_nextdoor_api.customer2')),
            ],
        ),
        migrations.AddField(
            model_name='customer2market',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_nextdoor_api.market2'),
        ),
        migrations.CreateModel(
            name='Vendor2Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_nextdoor_api.market2')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_nextdoor_api.vendor2')),
            ],
        ),
    ]
