# Generated by Django 5.0 on 2024-03-28 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='items',
        ),
        migrations.AddField(
            model_name='preorder',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='v2.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preorder',
            name='quantity_requested',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='PreorderItem',
        ),
    ]
